

vouch:
  logLevel: debug
  domains:
    - my-service-3blf5p4gxa-nw.a.run.app  # Changed from localhost
    - thehutgroup.com
  cookie:
    domain: my-service-3blf5p4gxa-nw.a.run.app  # Changed from localhost

    secure: false
  # URL that Vouch will redirect users to when they are not authenticated
  urls:
    login: https://my-service-3blf5p4gxa-nw.a.run.app/login  # Changed from localhost

oauth:
  provider: oidc
  client_id: "${OAUTH_CLIENT_ID}"
  client_secret: "${OAUTH_CLIENT_SECRET}"
  auth_url: https://thg.okta.com/oauth2/default/v1/authorize
  token_url: https://thg.okta.com/oauth2/default/v1/token
  user_info_url: https://thg.okta.com/oauth2/default/v1/userinfo
  scopes:
    - openid
    - email
    - profile
  # the callback url, which is the /auth endpoint in your deployment
  callback_url: https://my-service-3blf5p4gxa-nw.a.run.app/auth

